package MiniGames;


/**
* MiniGames/PlayerManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/idl/player.idl
* mardi 25 novembre 2025 15 h 02 WAT
*/

public interface PlayerManagerOperations 
{
  boolean registerPlayer (String name);
  String getOnlinePlayers ();
  String requestGame (String requester, String opponentName, String gameType);
  String getGameServerInfo (String gameType);
} // interface PlayerManagerOperations
