package MiniGames;


import org.omg.CORBA.*;
import org.omg.CORBA.Object;

/**
* MiniGames/PlayerManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/idl/player.idl
* mardi 25 novembre 2025 15 h 02 WAT
*/

public abstract class PlayerManagerPOA extends org.omg.PortableServer.Servant
 implements MiniGames.PlayerManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerPlayer", new java.lang.Integer (0));
    _methods.put ("getOnlinePlayers", new java.lang.Integer (1));
    _methods.put ("requestGame", new java.lang.Integer (2));
    _methods.put ("getGameServerInfo", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MiniGames/PlayerManager/registerPlayer
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.registerPlayer (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // MiniGames/PlayerManager/getOnlinePlayers
       {
         String $result = null;
         $result = this.getOnlinePlayers ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // MiniGames/PlayerManager/requestGame
       {
         String requester = in.read_string ();
         String opponentName = in.read_string ();
         String gameType = in.read_string ();
         String $result = null;
         $result = this.requestGame (requester, opponentName, gameType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // MiniGames/PlayerManager/getGameServerInfo
       {
         String gameType = in.read_string ();
         String $result = null;
         $result = this.getGameServerInfo (gameType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MiniGames/PlayerManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerManager _this() 
  {
    return PlayerManagerHelper.narrow(
    super._this_object());
  }

  public PlayerManager _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerManagerHelper.narrow(
    super._this_object(orb));
  }


    public abstract boolean _is_equivalent(Object other);

    public abstract int _hash(int maximum);

    public abstract Object _duplicate();

    public abstract void _release();

    public abstract Request _request(String operation);

    public abstract Request _create_request(Context ctx, String operation, NVList arg_list, NamedValue result);

    public abstract Request _create_request(Context ctx, String operation, NVList arg_list, NamedValue result, ExceptionList exclist, ContextList ctxlist);

    public abstract Policy _get_policy(int policy_type);

    public abstract DomainManager[] _get_domain_managers();

    public abstract Object _set_policy_override(Policy[] policies, SetOverrideType set_add);
} // class PlayerManagerPOA
