package MiniGames;

/**
* MiniGames/PlayerManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/idl/player.idl
* mardi 25 novembre 2025 15 h 02 WAT
*/

public final class PlayerManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public MiniGames.PlayerManager value = null;

  public PlayerManagerHolder ()
  {
  }

  public PlayerManagerHolder (MiniGames.PlayerManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MiniGames.PlayerManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MiniGames.PlayerManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MiniGames.PlayerManagerHelper.type ();
  }

}
