package MiniGames;


/**
* MiniGames/PlayerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/resources/idl/player.idl
* mardi 25 novembre 2025 15 h 02 WAT
*/

public interface PlayerManager extends PlayerManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerManager
