package MiniGames;


/**
* MiniGames/PlayerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PlayerManager.idl
* mardi 25 novembre 2025 14 h 41 WAT
*/

public interface PlayerManager extends PlayerManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PlayerManager
